// client/src/lib/types.ts

// =====================================================
// SHARED
// =====================================================

export type UUID = string;

export type StockStatus = "in_stock" | "limited" | "out_of_stock";
export type OrderStatus = "pending" | "processing" | "shipped" | "delivered" | "cancelled";
export type DiscountType = "percentage" | "fixed";

// MySQL timestamps coming as string
export type Timestamp = string;

// =====================================================
// USERS
// =====================================================

export type UserProfile = {
  id: UUID;
  email: string;
  password_hash?: string; // never use in UI, but exists in DB
  first_name: string;
  last_name: string;
  phone: string;
  is_admin: boolean;
  created_at: Timestamp;
  updated_at: Timestamp;
};

export type UserAddress = {
  id: UUID;
  user_id: UUID;
  first_name: string;
  last_name: string;
  email: string;
  phone: string;
  address_line1: string;
  address_line2: string;
  town: string;
  postal_code: string;
  country: string;
  is_default: boolean;
  created_at: Timestamp;
};

// =====================================================
// PRODUCT CATEGORIES (product_categories + pivot)
// =====================================================

export type ProductCategory = {
  id: UUID;
  parent_id: UUID | null;
  name: string;
  slug: string;
  description: string | null;
  image_url: string | null;
  display_order: number;
  created_at: Timestamp;
  updated_at: Timestamp;
};

export type ProductImage = {
  id: UUID;
  product_id: UUID;
  image_url: string;
  alt_text: string | null;
  display_order: number;
  is_primary: boolean;
  created_at: Timestamp;
};

export type ProductReview = {
  id: UUID;
  product_id: UUID;
  customer_name: string;
  customer_email: string;
  rating: number; // 1..5
  title: string | null;
  comment: string | null;
  is_verified_purchase: boolean;
  helpful_count: number;
  created_at: Timestamp;
  updated_at: Timestamp;
};

export type Product = {
  id: UUID;
  name: string;
  slug: string;
  description: string | null;
  short_description: string | null;

  // DB is DECIMAL(10,2) so it may come as string depending on driver
  price: number | string;
  compare_at_price: number | string | null;

  image_url: string | null;

  stock_status: StockStatus;
  is_featured: boolean;
  is_new: boolean;

  ingredients: string | null;
  usage: string | null;
  suitability: string | null;
  formula_benefits: string | null;
  cure_duration: string | null;
  usage_advice: string | null;
  composition: string | null;
  precautions: string | null;

  // DB is JSON; API parses, but keep safe
  benefits: string[];

  average_rating: number | string;
  review_count: number;

  created_at: Timestamp;
  updated_at: Timestamp;

  // Relations (from API)
  categories?: ProductCategory[];
  images?: ProductImage[];
  reviews?: ProductReview[];
};

export type ProductCategoryPivot = {
  product_id: UUID;
  category_id: UUID;
};

// =====================================================
// BLOG (blog_posts + blog_categories + pivot)
// =====================================================

export type BlogCategory = {
  id: UUID;
  parent_id: UUID | null;
  name: string;
  slug: string;
  description: string | null;
  image_url: string | null;
  display_order: number;
  created_at: Timestamp;
  updated_at: Timestamp;
};

export type BlogPost = {
  id: UUID;
  title: string;
  slug: string;
  excerpt: string | null;
  content: string;
  image_url: string | null;
  reading_time: number;
  views: number;
  published_at: Timestamp | null;
  created_at: Timestamp;
  updated_at: Timestamp;

  // Relations (from API)
  categories?: BlogCategory[];
};

export type BlogPostCategoryPivot = {
  blog_post_id: UUID;
  category_id: UUID;
};

// =====================================================
// ORDERS
// =====================================================

export type Order = {
  id: UUID;
  user_id: UUID | null;
  order_number: string | null; // generated by trigger, but column allows null
  status: OrderStatus;

  subtotal: number | string;
  discount_amount: number | string;
  total: number | string;

  coupon_id: UUID | null;

  shipping_first_name: string | null;
  shipping_last_name: string | null;
  shipping_email: string | null;
  shipping_phone: string | null;
  shipping_address_line1: string | null;
  shipping_address_line2: string | null;
  shipping_town: string | null;
  shipping_postal_code: string | null;
  shipping_country: string | null;

  notes: string | null;

  created_at: Timestamp;
  updated_at: Timestamp;
};

export type OrderItem = {
  id: UUID;
  order_id: UUID;
  product_id: UUID | null;
  product_name: string | null;
  product_price: number | string | null;
  quantity: number;
  subtotal: number | string | null;
  created_at: Timestamp;
};

// =====================================================
// COUPONS
// =====================================================

export type Coupon = {
  id: UUID;
  code: string;
  description: string;
  discount_type: DiscountType;
  discount_value: number | string;

  min_purchase_amount: number | string;
  max_discount_amount: number | string | null;

  valid_from: Timestamp;
  valid_until: Timestamp | null;

  usage_limit_per_user: number;
  total_usage_limit: number | null;
  current_usage_count: number;

  is_active: boolean;

  requires_first_order: boolean;
  requires_min_orders: number;

  created_at: Timestamp;
};

export type CouponUsage = {
  id: UUID;
  coupon_id: UUID | null;
  user_id: UUID | null;
  order_id: UUID | null;
  discount_applied: number | string | null;
  created_at: Timestamp;
};

// =====================================================
// FAQ
// =====================================================

export type FAQ = {
  id: UUID;
  question: string | null;
  answer: string | null;
  category: string | null;
  display_order: number;
  created_at: Timestamp;
  updated_at: Timestamp;
};
